# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen'}])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Food Groups (CHO: Carboidratos / PTN: Proteínas / LIP: Lipídeos / KCAL: KiloCalorias)
FoodGroup.create([{group:'Vegetais A'},{cho: 0},{ptn: 0},{lip: 0},{kcal: 0}])
FoodGroup.create([{group:'Vegetais B'},{cho: 8},{ptn: 2},{lip: 1},{kcal: 49}])
FoodGroup.create([{group:'Frutas'},{cho: 16 },{ptn: 0.5},{lip: 0.6},{kcal: 75.0}])
FoodGroup.create([{group:'Arroz '},{cho:  27 },{ptn: 3.5},{lip: 3},{kcal: 149}])
FoodGroup.create([{group:'Carnes'},{cho: 2},{ptn: 17 },{lip: 10 },{kcal: 164.0}])
FoodGroup.create([{group:'Leites e Derivados'},{cho: 6},{ptn: 9},{lip: 7},{kcal: 123}])
FoodGroup.create([{group:'Desnatado e soja'},{cho: 9.5},{ptn: 6},{lip: 1.5},{kcal: 75.5}])
FoodGroup.create([{group:'Gorduras'},{cho: 0},{ptn: 0},{lip: 6},{kcal: 54}])
FoodGroup.create([{group:'Embutidos '},{cho:  1},{ptn: 6.5},{lip: 2},{kcal: 48}])
FoodGroup.create([{group:'Feijões '},{cho:  10 },{ptn: 3.5},{lip: 0.5},{kcal: 58.5}])
FoodGroup.create([{group:'Pães'},{cho: 24 },{ptn: 3.5},{lip: 5},{kcal: 145}])
FoodGroup.create([{group:'Fibras'},{cho: 4.5},{ptn: 2},{lip: 2.5},{kcal: 48.5}])
FoodGroup.create([{group:'Açúcar'},{cho: 14 },{ptn: 1},{lip: 2},{kcal: 78}])


#Equivalent Foods
EquivalentFood.create([{food: 'Pepino'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Repolho'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Alface'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Agrião'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Aspargo'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Nabo'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Cebola'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Rabanete'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Tomate'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Espinafre'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Palmito'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Escarola'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Brócolis'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Couve-flor'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Alho'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Maxixe'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Almeirão'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Couve-manteiga'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Pimentão'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Limão'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Salsa'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Cebolinha'},{quantity_measure: 0},{measure: ''},{weight: 0},{group_id: 1}])
EquivalentFood.create([{food: 'Cenoura cozida'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 100},{group_id: 2}])
EquivalentFood.create([{food: 'Cenoura crua'},{quantity_measure: 8},{measure: 'colheres de sopa'},{weight: 100},{group_id: 2}])
EquivalentFood.create([{food: 'Beterraba cozida'},{quantity_measure: 5},{measure: 'colheres de sopa'},{weight: 100},{group_id: 2}])
EquivalentFood.create([{food: 'Beterraba crua'},{quantity_measure: 5},{measure: 'colheres de sopa'},{weight: 100},{group_id: 2}])
EquivalentFood.create([{food: 'Abóbora cabotiã cozida'},{quantity_measure: 2},{measure: 'colher de sopa cheia'},{weight: 72},{group_id: 2}])
EquivalentFood.create([{food: 'Abobrinha verde'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 90},{group_id: 2}])
EquivalentFood.create([{food: 'Chuchu cozido'},{quantity_measure: 5},{measure: 'colheres de sopa'},{weight: 100},{group_id: 2}])
EquivalentFood.create([{food: 'Berinjela cozida'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 75},{group_id: 2}])
EquivalentFood.create([{food: 'Jiló refogado'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 60},{group_id: 2}])
EquivalentFood.create([{food: 'Jiló cozido'},{quantity_measure: 2},{measure: 'colheres de sopa rasa'},{weight: 60},{group_id: 2}])
EquivalentFood.create([{food: 'Maxixe refogado'},{quantity_measure: 4},{measure: 'colheres de sopa rasa'},{weight: 100},{group_id: 2}])
EquivalentFood.create([{food: 'Quiabo refogado'},{quantity_measure: 2},{measure: 'colheres de sopa rasa'},{weight: 60},{group_id: 2}])
EquivalentFood.create([{food: 'Repolho refogado'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 72},{group_id: 2}])
EquivalentFood.create([{food: 'Abacate'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 45},{group_id: 3}])
EquivalentFood.create([{food: 'Abacaxi'},{quantity_measure: 1},{measure: 'fatia grande'},{weight: 100},{group_id: 3}])
EquivalentFood.create([{food: 'Acerola'},{quantity_measure: 20},{measure: 'unidades'},{weight: 120},{group_id: 3}])
EquivalentFood.create([{food: 'Ameixa fresca'},{quantity_measure: 3},{measure: 'unidades'},{weight: 150},{group_id: 3}])
EquivalentFood.create([{food: 'Banana prata'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 80},{group_id: 3}])
EquivalentFood.create([{food: 'Banana maçã'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 65},{group_id: 3}])
EquivalentFood.create([{food: 'Banana nanica'},{quantity_measure: 0.5},{measure: 'unidade'},{weight: 50},{group_id: 3}])
EquivalentFood.create([{food: 'Caqui'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 100},{group_id: 3}])
EquivalentFood.create([{food: 'Cajá'},{quantity_measure: 2},{measure: 'unidades'},{weight: 0},{group_id: 3}])
EquivalentFood.create([{food: 'Carambola'},{quantity_measure: 2},{measure: 'unidades'},{weight: 160},{group_id: 3}])
EquivalentFood.create([{food: 'Goiaba'},{quantity_measure: 1},{measure: 'unidade pequena'},{weight: 120},{group_id: 3}])
EquivalentFood.create([{food: 'Jaca'},{quantity_measure: 10},{measure: 'bagos'},{weight: 120},{group_id: 3}])
EquivalentFood.create([{food: 'Kiwi'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 76},{group_id: 3}])
EquivalentFood.create([{food: 'Laranja'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 180},{group_id: 3}])
EquivalentFood.create([{food: 'Maçã'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 130},{group_id: 3}])
EquivalentFood.create([{food: 'Mamão formosa'},{quantity_measure: 1},{measure: 'fatia média'},{weight: 170},{group_id: 3}])
EquivalentFood.create([{food: 'Mamão papaia'},{quantity_measure: 1},{measure: 'copo americano picado'},{weight: 165},{group_id: 3}])
EquivalentFood.create([{food: 'Manga espada'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 140},{group_id: 3}])
EquivalentFood.create([{food: 'Melancia'},{quantity_measure: 1},{measure: 'fatia grande'},{weight: 170},{group_id: 3}])
EquivalentFood.create([{food: 'Melão'},{quantity_measure: 2},{measure: 'fatias grandes'},{weight: 230},{group_id: 3}])
EquivalentFood.create([{food: 'Morango'},{quantity_measure: 15},{measure: 'unidades médias'},{weight: 180},{group_id: 3}])
EquivalentFood.create([{food: 'Mexerica'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 0},{group_id: 3}])
EquivalentFood.create([{food: 'Pêra'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 110},{group_id: 3}])
EquivalentFood.create([{food: 'Pêssego'},{quantity_measure: 2},{measure: 'unidades médias'},{weight: 120},{group_id: 3}])
EquivalentFood.create([{food: 'Uva'},{quantity_measure: 10},{measure: 'bagos médios'},{weight: 80},{group_id: 3}])
EquivalentFood.create([{food: 'Arroz branco'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 120},{group_id: 4}])
EquivalentFood.create([{food: 'Arroz integral'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 80},{group_id: 4}])
EquivalentFood.create([{food: 'Angu'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 105},{group_id: 4}])
EquivalentFood.create([{food: 'Batata doce'},{quantity_measure: 3},{measure: 'colheres de sopa picada'},{weight: 126},{group_id: 4}])
EquivalentFood.create([{food: 'Batatinha cozida'},{quantity_measure: 1},{measure: 'unidade média'},{weight: 140},{group_id: 4}])
EquivalentFood.create([{food: 'Batatinha frita'},{quantity_measure: 1},{measure: 'pires de chá'},{weight: 50},{group_id: 4}])
EquivalentFood.create([{food: 'Cará'},{quantity_measure: 2},{measure: 'colheres de sopa picada'},{weight: 0},{group_id: 4}])
EquivalentFood.create([{food: 'Farinha de mandioca'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 32},{group_id: 4}])
EquivalentFood.create([{food: 'Macarrão ao sugo'},{quantity_measure: 6},{measure: 'colheres de sopa'},{weight: 150},{group_id: 4}])
EquivalentFood.create([{food: 'Mandioca cozida'},{quantity_measure: 2},{measure: 'pedaços médios'},{weight: 120},{group_id: 4}])
EquivalentFood.create([{food: 'Pirão'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 120},{group_id: 4}])
EquivalentFood.create([{food: 'Purê de batata'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 135},{group_id: 4}])
EquivalentFood.create([{food: 'Lazanha a bolonhesa'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 110},{group_id: 4}])
EquivalentFood.create([{food: 'Milho verde cozido'},{quantity_measure: 7},{measure: 'colheres de sopa'},{weight: 168},{group_id: 4}])
EquivalentFood.create([{food: 'Pizza de calabreza'},{quantity_measure: 1},{measure: 'fatia pequena'},{weight: 45},{group_id: 4}])
EquivalentFood.create([{food: 'Pizza de mussarela'},{quantity_measure: 1},{measure: 'fatia pequena'},{weight: 50},{group_id: 4}])
EquivalentFood.create([{food: 'Sopa de legumes com carne sem macarrão (repolho, batata, cenoura e carne)'},{quantity_measure: 1},{measure: 'prato raso'},{weight: 325},{group_id: 4}])
EquivalentFood.create([{food: 'Maionese de legumes'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 114},{group_id: 4}])
EquivalentFood.create([{food: 'Atum em água e sal'},{quantity_measure: 6},{measure: 'colheres de sopa'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Sardinha'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 60},{group_id: 5}])
EquivalentFood.create([{food: 'Almôndegas de carne'},{quantity_measure: 2},{measure: 'unidades médias'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Bife de fígado'},{quantity_measure: 1},{measure: 'bife pequeno'},{weight: 80},{group_id: 5}])
EquivalentFood.create([{food: 'Bife'},{quantity_measure: 1},{measure: 'bife pequeno'},{weight: 80},{group_id: 5}])
EquivalentFood.create([{food: 'Bife à milanesa'},{quantity_measure: 1},{measure: 'bife bem peq.'},{weight: 55},{group_id: 5}])
EquivalentFood.create([{food: 'Carne moída'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Carne ao molho'},{quantity_measure: 3},{measure: 'ped. médios'},{weight: 105},{group_id: 5}])
EquivalentFood.create([{food: 'Carne seca'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 36},{group_id: 5}])
EquivalentFood.create([{food: 'Costela assada'},{quantity_measure: 1},{measure: 'pedaço médio'},{weight: 40},{group_id: 5}])
EquivalentFood.create([{food: 'Costelinha de porco'},{quantity_measure: 1},{measure: 'pedaço pequeno'},{weight: 40},{group_id: 5}])
EquivalentFood.create([{food: 'Sobrecoxa ao molho'},{quantity_measure: 1},{measure: 'unidade grande'},{weight: 95},{group_id: 5}])
EquivalentFood.create([{food: 'Asa ao molho'},{quantity_measure: 2},{measure: 'unidades'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Frango a passarinho'},{quantity_measure: 7},{measure: 'unidades pequenos'},{weight: 112},{group_id: 5}])
EquivalentFood.create([{food: 'Salsicha'},{quantity_measure: 1},{measure: 'unidade'},{weight: 50},{group_id: 5}])
EquivalentFood.create([{food: 'Salsicha de frango'},{quantity_measure: 1},{measure: 'unidade'},{weight: 50},{group_id: 5}])
EquivalentFood.create([{food: 'Strogonof de carne'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Strogonof de frango'},{quantity_measure: 4},{measure: 'colheres de sopa'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Peito de frango grelhado'},{quantity_measure: 1},{measure: 'filé médio'},{weight: 120},{group_id: 5}])
EquivalentFood.create([{food: 'Hamburguer bovino'},{quantity_measure: 1},{measure: 'unidade'},{weight: 56},{group_id: 5}])
EquivalentFood.create([{food: 'Hamburguer frango'},{quantity_measure: 1},{measure: 'unidade'},{weight: 56},{group_id: 5}])
EquivalentFood.create([{food: 'Hamburguer peru light'},{quantity_measure: 1},{measure: 'unidade'},{weight: 56},{group_id: 5}])
EquivalentFood.create([{food: 'Lingüiça toscana'},{quantity_measure: 1},{measure: 'unidade'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Lingüiça de frango'},{quantity_measure: 1},{measure: 'unidade'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Carne assada'},{quantity_measure: 1},{measure: 'fatia pequena'},{weight: 75},{group_id: 5}])
EquivalentFood.create([{food: 'Feijoada caseira'},{quantity_measure: 1},{measure: 'concha média'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Dobradinha'},{quantity_measure: 1},{measure: 'concha média'},{weight: 150},{group_id: 5}])
EquivalentFood.create([{food: 'Bisteca de porco grelhada'},{quantity_measure: 1},{measure: 'unidade pequena'},{weight: 80},{group_id: 5}])
EquivalentFood.create([{food: 'Lombo assado'},{quantity_measure: 1},{measure: 'fatia pequena'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Ovo cozido'},{quantity_measure: 2},{measure: 'unidades'},{weight: 100},{group_id: 5}])
EquivalentFood.create([{food: 'Ovo frito'},{quantity_measure: 1},{measure: 'unidade'},{weight: 50},{group_id: 5}])
EquivalentFood.create([{food: 'Ovos de codorna'},{quantity_measure: 12},{measure: 'unidades'},{weight: 108},{group_id: 5}])
EquivalentFood.create([{food: 'Clara de ovo'},{quantity_measure: 9},{measure: 'unidades'},{weight: 270},{group_id: 5}])
EquivalentFood.create([{food: 'Carne de soja (pts)'},{quantity_measure: 1},{measure: 'xícara'},{weight: 50},{group_id: 5}])
EquivalentFood.create([{food: 'Queijo Mussarela'},{quantity_measure: 2},{measure: 'fatias finas'},{weight: 40},{group_id: 6}])
EquivalentFood.create([{food: 'Queijo prato'},{quantity_measure: 2},{measure: 'fatias médias'},{weight: 30},{group_id: 6}])
EquivalentFood.create([{food: 'Queijo minas fresco'},{quantity_measure: 2},{measure: 'fatias médias'},{weight: 60},{group_id: 6}])
EquivalentFood.create([{food: 'Queijo tofu ou de soja'},{quantity_measure: 2},{measure: 'fatias grandes'},{weight: 76},{group_id: 6}])
EquivalentFood.create([{food: 'Queijo provolone'},{quantity_measure: 2},{measure: 'fatias médias'},{weight: 30},{group_id: 6}])
EquivalentFood.create([{food: 'Queijo polenguinho'},{quantity_measure: 2},{measure: 'unidades'},{weight: 40},{group_id: 6}])
EquivalentFood.create([{food: 'Requeijão cremoso'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 30},{group_id: 6}])
EquivalentFood.create([{food: 'Iogurte natural'},{quantity_measure: 1},{measure: 'pote'},{weight: 170},{group_id: 6}])
EquivalentFood.create([{food: 'Danoninho'},{quantity_measure: 2},{measure: 'potes'},{weight: 0},{group_id: 6}])
EquivalentFood.create([{food: 'Leite integral'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 6}])
EquivalentFood.create([{food: 'Coalhada integral'},{quantity_measure: 0.5},{measure: 'copo americano'},{weight: 130},{group_id: 6}])
EquivalentFood.create([{food: 'Piracanjuba com Quinoa e linhaça'},{quantity_measure: 1},{measure: 'pote'},{weight: 200},{group_id: 6}])
EquivalentFood.create([{food: 'Leite sem lactose Piracanjuba'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 6}])
EquivalentFood.create([{food: 'Iogurte de fruta'},{quantity_measure: 1},{measure: 'pote'},{weight: 120},{group_id: 6}])
EquivalentFood.create([{food: 'Leite desnatado'},{quantity_measure: 1},{measure: 'copo de requeijão'},{weight: 250},{group_id: 6}])
EquivalentFood.create([{food: 'Iogurte desnatado'},{quantity_measure: 1},{measure: 'unidade'},{weight: 185},{group_id: 6}])
EquivalentFood.create([{food: 'Coalhada desnatada'},{quantity_measure: 0.5},{measure: 'copo americano'},{weight: 130},{group_id: 6}])
EquivalentFood.create([{food: 'Leite fermentado'},{quantity_measure: 2},{measure: 'unidades'},{weight: 100},{group_id: 6}])
EquivalentFood.create([{food: 'Ades Original'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 6}])
EquivalentFood.create([{food: 'Ades zero'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 6}])
EquivalentFood.create([{food: 'Leite de soja'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 6}])
EquivalentFood.create([{food: 'Leite desnatado'},{quantity_measure: 1},{measure: 'copo de requeijão'},{weight: 250},{group_id: 7}])
EquivalentFood.create([{food: 'Iogurte desnatado'},{quantity_measure: 1},{measure: 'unidade'},{weight: 185},{group_id: 7}])
EquivalentFood.create([{food: 'Coalhada desnatada'},{quantity_measure: 0.5},{measure: 'copo americano'},{weight: 130},{group_id: 7}])
EquivalentFood.create([{food: 'Leite fermentado'},{quantity_measure: 2},{measure: 'unidades'},{weight: 100},{group_id: 7}])
EquivalentFood.create([{food: 'Ades Original'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 7}])
EquivalentFood.create([{food: 'Ades zero'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 7}])
EquivalentFood.create([{food: 'Leite de soja'},{quantity_measure: 1},{measure: 'copo americano'},{weight: 200},{group_id: 7}])
EquivalentFood.create([{food: 'Azeite de oliva'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 8},{group_id: 8}])
EquivalentFood.create([{food: 'Azeite de dendê'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 8},{group_id: 8}])
EquivalentFood.create([{food: 'Óleo de soja, girassol, milho e canola'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 8},{group_id: 8}])
EquivalentFood.create([{food: 'Creme de leite'},{quantity_measure: 1},{measure: 'colher de sopa rasa'},{weight: 0},{group_id: 8}])
EquivalentFood.create([{food: 'Maionese'},{quantity_measure: 1},{measure: 'colher de sopa rasa'},{weight: 12},{group_id: 8}])
EquivalentFood.create([{food: 'Maionese light'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 12},{group_id: 8}])
EquivalentFood.create([{food: 'Manteiga de leite'},{quantity_measure: 1},{measure: 'colher de sopa rasa'},{weight: 0},{group_id: 8}])
EquivalentFood.create([{food: 'Margarina'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 0},{group_id: 8}])
EquivalentFood.create([{food: 'Margarina light'},{quantity_measure: 1},{measure: 'colher de sopa rasa'},{weight: 0},{group_id: 8}])
EquivalentFood.create([{food: 'Salame'},{quantity_measure: 4},{measure: 'fatias'},{weight: 20},{group_id: 9}])
EquivalentFood.create([{food: 'Apresuntado'},{quantity_measure: 2},{measure: 'fatias'},{weight: 30},{group_id: 9}])
EquivalentFood.create([{food: 'Presunto com capa de gordura'},{quantity_measure: 2},{measure: 'fatias'},{weight: 40},{group_id: 9}])
EquivalentFood.create([{food: 'Presunto sem capa de gordura'},{quantity_measure: 2},{measure: 'fatias'},{weight: 40},{group_id: 9}])
EquivalentFood.create([{food: 'Presunto de peru'},{quantity_measure: 4.5},{measure: 'fatias'},{weight: 40},{group_id: 9}])
EquivalentFood.create([{food: 'Blanquet de peru'},{quantity_measure: 8},{measure: 'fatias'},{weight: 60},{group_id: 9}])
EquivalentFood.create([{food: 'Feijão cozido'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 58},{group_id: 10}])
EquivalentFood.create([{food: 'Ervilha cozida'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 81},{group_id: 10}])
EquivalentFood.create([{food: 'Soja cozida'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 34},{group_id: 10}])
EquivalentFood.create([{food: 'Lentilha'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 48},{group_id: 10}])
EquivalentFood.create([{food: 'Grão de bico cozido'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 44},{group_id: 10}])
EquivalentFood.create([{food: 'Pão francês'},{quantity_measure: 1},{measure: 'unidade'},{weight: 50},{group_id: 11}])
EquivalentFood.create([{food: 'Aveia em flocos'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 45},{group_id: 11}])
EquivalentFood.create([{food: 'Quebrador'},{quantity_measure: 3},{measure: 'unidades'},{weight: 30},{group_id: 11}])
EquivalentFood.create([{food: 'Pão integral'},{quantity_measure: 2},{measure: 'fatias'},{weight: 50},{group_id: 11}])
EquivalentFood.create([{food: 'Pão de hambúrguer'},{quantity_measure: 1},{measure: 'unidade'},{weight: 70},{group_id: 11}])
EquivalentFood.create([{food: 'Pão caseiro'},{quantity_measure: 1},{measure: 'fatia média'},{weight: 50},{group_id: 11}])
EquivalentFood.create([{food: 'Pão de forma'},{quantity_measure: 2},{measure: 'fatias'},{weight: 50},{group_id: 11}])
EquivalentFood.create([{food: 'Pão de queijo'},{quantity_measure: 2},{measure: 'unidades pequenas'},{weight: 40},{group_id: 11}])
EquivalentFood.create([{food: 'Granola'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 33},{group_id: 11}])
EquivalentFood.create([{food: 'Farinha láctea'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 40},{group_id: 11}])
EquivalentFood.create([{food: 'Bolo comum'},{quantity_measure: 1},{measure: 'fatia pequena'},{weight: 40},{group_id: 11}])
EquivalentFood.create([{food: 'Bolacha recheada'},{quantity_measure: 2},{measure: 'unidades'},{weight: 27},{group_id: 11}])
EquivalentFood.create([{food: 'Bolacha wafer'},{quantity_measure: 3},{measure: 'unidades'},{weight: 28},{group_id: 11}])
EquivalentFood.create([{food: 'Bolacha maizena'},{quantity_measure: 7},{measure: 'unidades'},{weight: 30},{group_id: 11}])
EquivalentFood.create([{food: 'Bolacha Cream cracker'},{quantity_measure: 5},{measure: 'unidades'},{weight: 32},{group_id: 11}])
EquivalentFood.create([{food: 'Sucrilhos'},{quantity_measure: 3},{measure: 'colheres de sopa'},{weight: 43},{group_id: 11}])
EquivalentFood.create([{food: 'Pipoca'},{quantity_measure: 3},{measure: 'xícaras de chá'},{weight: 27},{group_id: 11}])
EquivalentFood.create([{food: 'Torrada de pão francês'},{quantity_measure: 6},{measure: 'fatias'},{weight: 33},{group_id: 11}])
EquivalentFood.create([{food: 'Cuscuz de milharina'},{quantity_measure: 1},{measure: 'pedaço pequeno'},{weight: 85},{group_id: 11}])
EquivalentFood.create([{food: 'Semente de linhaça'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 15},{group_id: 12}])
EquivalentFood.create([{food: 'Gergelim'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 8},{group_id: 12}])
EquivalentFood.create([{food: 'Germe de trigo'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 15},{group_id: 12}])
EquivalentFood.create([{food: 'Farelo de trigo'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 9},{group_id: 12}])
EquivalentFood.create([{food: 'Semente de girassol'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 12},{group_id: 12}])
EquivalentFood.create([{food: 'Farinha de maracujá'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 10},{group_id: 12}])
EquivalentFood.create([{food: 'Farinha de aveia'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 16},{group_id: 12}])
EquivalentFood.create([{food: 'Quinoa'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 9.5},{group_id: 12}])
EquivalentFood.create([{food: 'Chia'},{quantity_measure: 1.5},{measure: 'colher de sopa'},{weight: 15},{group_id: 12}])
EquivalentFood.create([{food: 'Açúcar branco'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 24},{group_id: 13}])
EquivalentFood.create([{food: 'Açúcar mascavo'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 19},{group_id: 13}])
EquivalentFood.create([{food: 'Nescau'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 20},{group_id: 13}])
EquivalentFood.create([{food: 'Nescau light'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 19},{group_id: 13}])
EquivalentFood.create([{food: 'Toddy'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 20},{group_id: 13}])
EquivalentFood.create([{food: 'Toddy light'},{quantity_measure: 2},{measure: 'colheres de sopa'},{weight: 20},{group_id: 13}])
EquivalentFood.create([{food: 'Brigadeiro'},{quantity_measure: 1},{measure: 'unidade pequena'},{weight: 15},{group_id: 13}])
EquivalentFood.create([{food: 'Mousse de maracujá'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 35},{group_id: 13}])
EquivalentFood.create([{food: 'Mousse de chocolate'},{quantity_measure: 1},{measure: 'colher de sopa'},{weight: 25},{group_id: 13}])
EquivalentFood.create([{food: 'Bis'},{quantity_measure: 2},{measure: 'unidades'},{weight: 15},{group_id: 13}])
EquivalentFood.create([{food: 'Chocolate amargo Talento 55% cacau'},{quantity_measure: 0.5},{measure: 'tablete de 25 gramas'},{weight: 12.5},{group_id: 13}])